
server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/development #change this to your database url
    password: root #change this to your database username
    username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: true


